baseURL = 'https://lambdagoat.com/'
languageCode = 'en-us'
title = 'Lambda Goat'
theme = 'lbgt'

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true