name = 'lbgt'
license = 'MIT'
licenselink = 'https://github.com/rschardt/lambdagoat-website/blob/main/themes/lbgt/LICENSE'
description = 'Lambda Goat Theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/rschardt/lambdagoat-website/tree/main/themes/lbgt'

# If you have a running demo of the theme
demosite = 'https://lambdagoat.com'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

[author]
  name = 'Robert Schardt'
  homepage = 'https://lambdagoat.com'
